### ISSUE TITLE
Missing stylelint-enable in scss/settings/_glyphs.scss

### ISSUE THREAD

**Issue by dawidchar** [justeat/fozzie#333]
There is a missing `stylelint-enable` at the end of the file for enabling style linting back for indentation, this will cause `"indentation" has already been disabled` error if another file afterwards uses `stylelint-disable indentation` 

https://github.com/justeat/fozzie/blob/09f454176bf59a28c1fa7678dfdb83d0cb7fec40/src/scss/settings/_glyphs.scss
https://github.com/justeat/fozzie/blob/09f454176bf59a28c1fa7678dfdb83d0cb7fec40/src/scss/settings/_glyphs.scss#L1-L7

 `stylelint-enable`  is done in the file below, to most likely prevent the above `stylelint-disable indentation` from erroring
https://github.com/justeat/fozzie/blob/09f454176bf59a28c1fa7678dfdb83d0cb7fec40/src/scss/settings/_variables.scss#L1
https://github.com/justeat/fozzie/blob/09f454176bf59a28c1fa7678dfdb83d0cb7fec40/src/scss/settings/_variables.scss#L176

**Comment by jamieomaguire** [comment]
Remind me why this issue only just surfaced for us @dawidchar? Presumably this has been missing for a while?

**Comment by dawidchar** [comment]
Because I assume no scss file after this file disables indentation, so it does not error or this error has just been ignored

I believe it's good practice to also reset any global linting rules (because these rules are global) after using them temporarily in a file, the documentation does something similar https://stylelint.io/user-guide/ignore-code/

**Comment by dawidchar** [comment]
Ah, this file has been removed in Fozzie 5, so I'll close the issue 🥳
