### ISSUE TITLE
CPD-11417 — Switch from using `babel-preset-es2015` to `babel-preset-env`

### ISSUE THREAD

**Issue by DamianMullins** [justeat/fozzie#44]
The `babel-preset-env` preset checks the `"browserslist"` section of the `package.json` file to determine which features should be transpiled as part of the JavaScript build process.

There is a good chance that [the yearly preset packages will be deprecated soon](deprecated-yearly-presets-eg-babel-preset-es20xx), so moving over to use the `env` preset should be carried out soon.

As long as our packages each have a `"browserslist"` section in the `package.json` file this change should be fairly trivial — the longest (most boring) part will be making the change in every one of our modules and projects.

---

Currently, the only project which has made the switch is the [`f-templates`](https://github.com/justeat/f-templates/blob/3145272963f2459deaf57b0990d74a9c04f25636/.babelrc#L3) module [which targets a version of Node](https://github.com/justeat/f-templates/blob/3145272963f2459deaf57b0990d74a9c04f25636/package.json#L49) rather than a list of browsers.

--- 

## Final browserslist

```json
"browserslist": [
  "> 5%",
  "last 2 versions",
  "Safari >= 8",
  "not ie 10"
]
```

## Projects to update

- [x] [`fozzie`](https://github.com/justeat/fozzie)
- [x] [`global-component-library`](https://github.com/justeat/global-component-library)
- [x] [`f-templates`](https://github.com/justeat/f-templates)
- [x] [`f-validate`](https://github.com/justeat/f-validate)
- [x] [`f-dom`](https://github.com/justeat/f-dom)
- [x] [`f-toggle`](https://github.com/justeat/f-toggle)
- [x] [`f-header`](https://github.com/justeat/f-header) - browserslist needs to be updated
- [x] [`f-footer`](https://github.com/justeat/f-footer)
- [x] [`f-logger`](https://github.com/justeat/f-logger)
- [x] [`f-serviceworker`](https://github.com/justeat/f-serviceworker)

**Comment by ashleynolan** [comment]
Yep – we should definitely do this 👍 

All modules _should_ have a browserslist as autoprefixer hooks into this list for adding CSS prefixes.

**Comment by DamianMullins** [comment]
We want to update the `browserslist` so that only IE11 is included, however, if we update to include the `"ie > 10""` rule then [IE10 is *still* included because of the `last 2 versions rule`](http://browserl.ist/?q=%3E+5%25%2C+last+2+versions%2C+ie+%3E+10%2C+Safari+%3E%3D+8).

Adding the `not ie 10` rule [will exclude IE10](http://browserl.ist/?q=%3E+5%25%2C+last+2+versions%2C+ie+%3E+10%2C+Safari+%3E%3D+8%2C+not+ie+10).

**Comment by ashleynolan** [comment]
Yeh, makes sense to do that then.  I thought it would treat Edge as the latest 😠

**Comment by ashleynolan** [comment]
I've put in PRs for Fozzie and the Global component library now for this.  Will update the others later today too

**Comment by ashleynolan** [comment]
Have updated all of the modules listed here now to using the latest babel preset and `browserslist`.
