### ISSUE TITLE
Support node 9.x

### ISSUE THREAD

**Issue by martincostello** [justeat/fozzie#92]
Due to the dependency chain of fozzie with its current version of `node-sass`, it cannot be used on machines with node 9.x installed without _also_ having Python installed so the tool chain can compile an appropriate binary for itself.

This creates lots of complications internally as the TeamCity default is node 9, meaning we need to use a custom image with node 6 on it to be able to run gulp for applications using fozzie.

Newer versions of `node-sass` support node 9.x, but the upgrade process isn't simple because that upgrade breaks other things.

**Comment by martincostello** [comment]
So what was happening was:
  1. node-saas would say that node 9 wasn't supported because whatever pre-compiled binary it wanted from [here](https://github.com/sass/node-sass/releases/tag/v4.8.3) (`win32-x64-something`).
  1. It would then try a compile a native binary by itself to support node 9.
  1. The native compilation would fail because Python 3 isn't installed on the TeamCity agent.

Updating the node-sass dependency in `package.json` in the application fixed the node incompatibility, but then created issues for other dependencies that seemed to be "hard-coded" somehow to look at the wrong version on disk in `node_packages` in sub-directories of other dependencies, so would then fail the build anyway for completely different reasons.

It may be that later versions of Fozzie have changed their dependency tree in such a way that this happens to have fixed itself?

If you try and do a build of GlobalWeb, OrderWeb or SearchWeb using the node9 TeamCity agent, either it'll now work and this can be closed, or it'll fail and produce an error because it's trying to compile node-sass's native binary itself.

**Comment by ashleynolan** [comment]
Cheers for the detail.  I'm off Thurs/Fri but will pick this up next week and see if I can resolve it.

**Comment by DamianMullins** [comment]
Has this now been resolved by using Node v8 in our builds?

**Comment by ashleynolan** [comment]
It should be I think.  We shouldn't have to support Node 9 (as it's a non-LTS version), so the next version that we'll need to support will be 10.

Once that gets made the new LTS version we'll have to move our Travis builds over to do this (which will be in October).

**Comment by martincostello** [comment]
Yeah, I'm happy that the "spirit" of this ticket (_be able to use newer versions of node than 6_) is resolved.
