### ISSUE TITLE
Splitting out Fozzie JS modules.

### ISSUE THREAD

**Issue by sonnyprince** [justeat/fozzie#99]
In the latest Fozzie PR (v0.54.0) we have a new JS module - a simple JS input reset module.

There's been some discussion on the branch on how to approach the location / distribution of this, and future, JS modules to stop Fozzie getting weighty with unused stuff.

We could split it out - like f-analytics / f-dom.
Ash mentioned it could still live within fozzie but have it's own release template. 

@DamianMullins @ashleynolan @kevinrodrigues @justeat/ui-admins.

Thoughts? Preferred approach?

**Comment by ashleynolan** [comment]
Yep – the way I see it there are two options:

---

## Option 1 – Stored in Fozzie
Create a utilities folder in fozzie at `/src/js/utilities` where these utility modules are located.  Then each utility is stored inside it's own folder, which also has the info needed to publish it as a separate module to NPM.

So in this case we'd have a module called `formReset` which would be in a folder called at the location `/src/js/utilities/formReset`.  Code would be in an `index.js` at the root of this folder and it would have a `package.json` and any other needed config files that mean it could be released as a separate module that can be pulled in via NPM when needed in individual projects (so SearchWeb would then pull in this package via NPM).

## Option 2 – Stored in separate f-utlities repo

Make a `f-utilities` repo which stores all the js utilities that we create.

Pretty much the same as above, where each module has it's own folder and `package.json`, main difference is that it's in it's own repo, with a separate CHANGELOG and README.

---

I think I prefer option 2, simply as it will be a little more easy to keep track of utility modules being added/updated.  The CHANGELOG will likely be a bit clearer as it'll only have utility module specific info in it.

Thoughts?

**Comment by kevinrodrigues** [comment]
Option 2 takes my preference, split it out so it is it's own thing. :)

**Comment by sonnyprince** [comment]
Option 2! 
I'll get it done - will port this code into f-utilities and create a new PR!
